version: '3.7'

services:
  db:
    image: couchdb:3.3.2
    volumes:
      - db_data:/var/lib/couchdb
      - ./config/couchdb.ini:/opt/couchdb/etc/local.d/couchdb.ini # this is for couchdb config
    restart: unless-stopped
    environment:
      COUCHDB_USER: 4dm1n-us3r
      COUCHDB_PASSWORD: 4dm1n-p4ssw0rd!!
    ports:
      - 5984:5984

  datawarehouse:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - warehouse_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pgp4ssw0rd
      POSTGRES_DB: medicaly

  encode-orders:
    build: ../../packages/backend/ticket-codes
    restart: unless-stopped
    depends_on:
      - db
    environment:
      COUCHDB_URL: http://db:5984
      COUCHDB_USERNAME: 4dm1n-us3r
      COUCHDB_PASSWORD: 4dm1n-p4ssw0rd!!
      CRON_JOB_EXPRESSION: '30 * * * * *'

  ws-service:
    build: ../../packages/backend/ws-service
    restart: unless-stopped
    ports:
      - 3001:3001

  front:
    build: ../../packages/frontend
    restart: unless-stopped
    ports:
      - 80:80

  # redis:
  #   image: redis:latest
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379

  # minio:
  #   image: minio/minio:latest
  #   restart: unless-stopped
  #   volumes:
  #     - minio_data:/data
  #   ports:
  #     - 9000:9000
  #   environment:
  #     MINIO_ACCESS_KEY: 4dm1n-us3r
  #     MINIO_SECRET_KEY: 4dm1n-p4ssw0rd!!

volumes:
  db_data:
  warehouse_data:
  # minio_data:
