version: '3.7'
services:
  proxy:
    image: caddy:2.4.5
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - ./config/certs:/data/caddy

  db:
    image: couchdb:3.3.3
    volumes:
      - db_data:/opt/couchdb/data # this is for couchdb data
      # - db_data:/var/lib/couchdb
      - ./config/couchdb.ini:/opt/couchdb/etc/local.d/couchdb.ini # this is for couchdb config
    restart: unless-stopped
    environment:
      COUCHDB_USER: 4dm1n-us3r
      COUCHDB_PASSWORD: 4dm1n-p4ssw0rd!!
    ports:
      - 5984:5984

  api-gateway:
    build: ../../packages/backend/api-gateway
    restart: unless-stopped
    depends_on:
      - db
    environment:
      COUCHDB_URL: http://db:5984
      COUCHDB_USERNAME: 4dm1n-us3r
      COUCHDB_PASSWORD: 4dm1n-p4ssw0rd!!
      FRONTEND_URL: http://localhost:5173
      PORT: 4000

  datawarehouse:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - warehouse_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pgp4ssw0rd
      POSTGRES_DB: medicaly

  encode-orders:
    build: ../../packages/backend/ticket-codes
    restart: unless-stopped
    depends_on:
      - db
    environment:
      COUCHDB_URL: http://db:5984
      COUCHDB_USERNAME: 4dm1n-us3r
      COUCHDB_PASSWORD: 4dm1n-p4ssw0rd!!
      CRON_JOB_EXPRESSION: '5 * * * * *'

  datawarehouse-sync:
    build: ../../packages/backend/datawarehouse-sync
    restart: unless-stopped
    depends_on:
      - db
      - datawarehouse
    environment:
      COUCHDB_URL: http://db:5984
      COUCHDB_USERNAME: 4dm1n-us3r
      COUCHDB_PASSWORD: 4dm1n-p4ssw0rd!!
      CRON_JOB_EXPRESSION: '30 * * * * *'
      WAREHOUSE_DB_URL: postgres://postgres:pgp4ssw0rd@datawarehouse:5432/medicaly

  ws-service:
    build: ../../packages/backend/ws-service
    restart: unless-stopped
    ports:
      - 3001:3001

  front:
    build: ../../packages/frontend
    restart: unless-stopped
    # ports:
    #   - 80:80

  metabase:
    image: metabase/metabase
    restart: unless-stopped
    depends_on:
      - datawarehouse
    ports:
      - 3000:3000

  # redis:
  #   image: redis:latest
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379

  # minio:
  #   image: minio/minio:latest
  #   restart: unless-stopped
  #   volumes:
  #     - minio_data:/data
  #   ports:
  #     - 9000:9000
  #   environment:
  #     MINIO_ACCESS_KEY: 4dm1n-us3r
  #     MINIO_SECRET_KEY: 4dm1n-p4ssw0rd!!

  pdf-engine:
    image: gotenberg/gotenberg:8
    restart: unless-stopped
    ports:
      - 30000:3000

  certificates:
    build: ../../packages/backend/certificates
    restart: unless-stopped
    depends_on:
      - pdf-engine
    ports:
      - 3002:3002
    environment:
      GOTENBERG_ENDPOINT: http://pdf-engine:3000
      COUCHDB_URL: http://db:5984
      COUCHDB_USERNAME: 4dm1n-us3r
      COUCHDB_PASSWORD: 4dm1n-p4ssw0rd!!
      PORT: 3002

volumes:
  db_data:
  warehouse_data:
  # minio_data:
